/**
 * Worker entry point.
 *
 * Two things have to happen at module load:
 *
 * 1. The Durable Object class is exported, so wrangler can bind it (see
 *    wrangler.toml `[[durable_objects.bindings]]`).
 *
 * 2. All `@Route`-decorated route classes and `@EventHandler`-decorated event
 *    handlers are imported. Their decorators run as a side effect of import,
 *    populating the Ceves global registries. Import these BEFORE
 *    calling `createRouter()` — `createRouter()` snapshots the registry.
 *
 *    The barrel below (`_decoratorImports.generated.ts`) is produced by the
 *    `ceves-generate-imports` CLI as a `prebuild` / `predev` hook (see
 *    `package.json`). It contains one static `import './…';` per
 *    `commands/queries/events` file. We don't use `import.meta.glob({ eager:
 *    true })` because it only works under Vite — wrangler's esbuild bundler
 *    silently drops every match, which broke production deploys. A static
 *    barrel is portable across every bundler.
 *
 * Then `createRouter()` builds a Hono app with all registered routes wired up
 * and OpenAPI docs at /openapi.json + /docs.
 */

import { createRouter } from 'ceves';

// Generated barrel of every `@Route` / `@EventHandler` file under src/.
// Regenerated by `npm run gen:decorator-imports` (and as a prebuild hook).
import { REGISTERED_ROUTES } from './_decoratorImports.generated';

// Re-export the Durable Object class so wrangler can find it
export { BankAccountAggregate } from './aggregates/BankAccountAggregate';

const app = createRouter({
  // Explicit route surface: only classes in the generated barrel are exposed,
  // and a barrel entry missing its @Route metadata fails loudly at startup.
  routes: REGISTERED_ROUTES,
  openapi: {
    title: 'Ceves Example — BankAccount API',
    version: '1.0.0',
    description:
      'A minimal event-sourced bank-account service built on the Ceves library.',
  },
  docsPath: '/docs',
  schemaPath: '/openapi.json',
});

export default app;
