/**
 * PostgreSQL entry point — the module `ceves-generate-pg` bundles for PLV8.
 *
 * The PG variant runs the same command/query handlers, but INSIDE PostgreSQL:
 * state lives in `ceves.aggregate_state`, and processing happens in the
 * generated `ceves.execute_command` / `ceves.execute_query` PLV8 functions.
 * Events are returned to the HTTP wrapper (never stored in PostgreSQL).
 *
 * Three things must happen at module load, in order:
 *
 * 1. Import the generated decorator barrel so every `@Route` /
 *    `@EventHandler` registers (same rule as the worker and NATS entries).
 * 2. Register each aggregate's state class, replacing the DO subclass's
 *    `super(ctx, env, StateClass)` as the source of the ADR-009 empty state.
 * 3. Install the dispatcher on `globalThis` so the PLV8 functions can call it
 *    (and so the generator CLI can read the route manifest under Node).
 *
 * Generate the SQL with:
 *
 *   ceves-generate-pg --entry src/pg-entry.ts --out ceves-pg.sql
 */

// 1. Decorator registrations — importing the generated barrel runs every
//    @Route / @EventHandler decorator (same as src/index.ts and nats-main.ts).
//    Regenerated by `npm run gen:decorator-imports` (a pregen:pg hook).
import './_decoratorImports.generated';

import { registerPgAggregateState, installPlv8Dispatcher } from 'ceves/pg';
import { AccountState } from './aggregates/BankAccountAggregate.js';

// 2. State class per aggregate type (ADR-009 empty state for first events).
registerPgAggregateState('BankAccountAggregate', AccountState);

// 3. Install `globalThis.__ceves_pg__` for the PLV8 dispatch functions.
installPlv8Dispatcher();
